[fixed]
iShamSLam/HomeWork-1 pull request #2
Opened 2018-09-24 13:30 UTC by iShamSLam

2018-09-24 16:10 UTC, iShamSLam commented
https://pp.userapi.com/c850220/v850220901/35c5b/IOm81kK8KJA.jpg

2018-09-24 16:12 UTC, iShamSLam commented
![iom81kk8kja](https://user-images.githubusercontent.com/31825566/45964187-c2428200-c02d-11e8-94de-ba53609e5a4d.jpg)

2018-09-25 19:50 UTC, NailShaykhrazievItis requested changes

2018-09-25 19:50 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/java/com/example/user/homework/EditActivity.java
> +        etName.setText(intent.getStringExtra("name"));
Можешь на будущее константы для аргументов выносить в константы(неожиданно). Example:
psfs EXTRA_NAME="EXTRA_NAME"

2018-09-25 19:50 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/java/com/example/user/homework/EditActivity.java
> +        btnCancel.setOnClickListener(this);
В принципе все правильно, но удобнее для каждой кнопки писать свой метод. Example:
btnCancel.setOnClickListener(v -> onCancelClick());
private void onCancelClick() {
	// code
}

2018-09-25 19:50 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/java/com/example/user/homework/MainActivity.java
> +    static final int SET_DATA = 1;
Cтатика идет в начале класса. Глянуть саму первую презентацию по кодстайлу

2018-09-25 19:50 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/java/com/example/user/homework/EditActivity.java
> +        startActivity(intent);
Тут тебе надо было написать вместо стартактивити:
setResult(intent);
finish();

2018-09-25 19:50 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_edit.xml
> +    <EditText
Разделяй пустыми строками. Не читабельно

2018-10-02 23:09 UTC, closed without merging