[yraaaaa pilyat yje spina bolit ya umiray ]
iShamSLam/HomeWork-1 pull request #8
Opened 2018-11-12 22:41 UTC by iShamSLam

![screenshot_1542062279](https://user-images.githubusercontent.com/31825566/48379423-2e17a180-e6e5-11e8-91e7-d13b69d5d7be.png)
![screenshot_1542062285](https://user-images.githubusercontent.com/31825566/48379424-2eb03800-e6e5-11e8-8499-ea54e985ed74.png)
![screenshot_1542062290](https://user-images.githubusercontent.com/31825566/48379425-2eb03800-e6e5-11e8-89d3-1cae86b4a1ee.png)
![screenshot_1542062300](https://user-images.githubusercontent.com/31825566/48379426-2eb03800-e6e5-11e8-8a80-6d0c024b6694.png)
![screenshot_1542062303](https://user-images.githubusercontent.com/31825566/48379427-2f48ce80-e6e5-11e8-9b81-ba3bb4a6b75c.png)
![screenshot_1542062307](https://user-images.githubusercontent.com/31825566/48379429-2f48ce80-e6e5-11e8-98ec-5bf8ee604dea.png)
![screenshot_1542062311](https://user-images.githubusercontent.com/31825566/48379431-2f48ce80-e6e5-11e8-8511-bb90c6dfa05c.png)

2018-11-13 21:49 UTC, NailShaykhrazievItis requested changes

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="8dp"
у тебя со всех сторон одинаковые маргины, можешь использовать просто margin=8

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/pause"
iv_pause

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/skip_to_previous"
btn_

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/play"
iv_play

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="61dp"
Cтарайся выбирать значения которые делятся на 8

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on HomeWork/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/artist"
tv_artist

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Information.java
> +            playButton.setVisibility(View.INVISIBLE);
повторяющийся код можно вынести в отдельный метод

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/MediaStyleHelper.java
> +    static NotificationCompat.Builder from(
название метода должно говорить что он делает, тут особо нет. условно гетНотификейшен

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/MusicSpace.java
> +    static class Track {
Мог в отдельный класс вынести, это все таки энтити какое то, и убрать статик

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/PlayerService.java
> +final public class PlayerService extends Service {
почему класс должен быть не изменяемым?

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Recycle.java
> +public class Recycle extends AppCompatActivity {
RecycleActivity

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Recycle.java
> +    public Recycle() {
констуктор активити не нужен

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Track_Adapter.java
> +        holder.view.setOnClickListener(v -> holder.onClick(holder.itemView));
callBack.onClick(MusicSpace.Track track)

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Track_Adapter.java
> +        public void onClick(View view) {
Это должно лежать в активити. Не должен элемент уметь запускать другие экраны, это не его уровень ответсвенности

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Track_Adapter.java
> +public class Track_Adapter extends RecyclerView.Adapter<Track_Adapter.ViewHolder> {
TrackAdapter

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/java/com/example/user/homework/Recycle.java
> +            Intent intent = new Intent(this, Information.class);
Вот же есть у тебя клик

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/res/layout/single_item.xml
> +        android:id="@+id/name"
tv_ or text_name

2018-11-13 21:49 UTC, NailShaykhrazievItis commented on Homework/app/src/main/res/layout/single_item.xml
> +        android:layout_alignStart="@+id/name"
в констреинте нет такого поля

2018-11-14 13:13 UTC, Rishat7c commented
ne umiray

2018-11-26 20:13 UTC, closed without merging